// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzhjopgkfszffyezuetu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6aGpvcGdrZnN6ZmZ5ZXp1ZXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDg4MTUsImV4cCI6MjA2MDIyNDgxNX0.LRWSJh_v6g2qpF8qGr0Bak96uBqKV-DqqfQ6r6DqjH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);